%% Data Visualization
clc; clear all;
load data
%%
data_v = mydata_before_shuffling; % data_visualization
Fs = 16;
Ft = 20;
%% pre visualizaion on total data
t = categorical(data(:,11),[0 1],{'Healthy','Stroke'});
figure()
histogram(t,'BarWidth',0.5,'Facecolor','b');
title('total data = 5110 ',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
  
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
%% A. app
%% B:Histogram
%%   distribution of sex and age
sex_s = data_v(1:249,1);
age_s = data_v(1:249,2);
sex_h = data_v(250:end,1);
age_h = data_v(250:end,2);
figure()
scatterhist(sex_s,age_s)
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('sex','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
figure()
scatterhist(sex_h,age_h)
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('sex','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');

%%    1. sex
figure()
subplot(1,2,1)
c11 = categorical(data_v(1:249,1),[0 1],{'male','female'});
histogram(c11,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
  
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
subplot(1,2,2)
c12 = categorical(data_v(250:end,1),[0 1],{'male','female'});
histogram(c12,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])

%%   2. distribution age
figure()
subplot(1,2,1)
histogram(data_v(1:249,2),8,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
  
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
xlim([0 90])
ylim([0 100])
subplot(1,2,2)
histogram(data_v(250:end,2),8,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
xlim([0 90])
ylim([0 100])

mean_age_stroke = mean(data_v(1:249,2))
mean_age_healthy = mean(data_v(250:end,2))

%%   3. distribution hypertension
figure()
subplot(1,2,1)
c31 = categorical(data_v(1:249,3),[0 1],{'No Hypertension','with Hypertension'});
histogram(c31,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
  
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
subplot(1,2,2)
c32 = categorical(data_v(250:end,3),[0 1],{'No Hypertension','with Hypertension'});
histogram(c32,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
%%   4. distribution of heart disease
figure()
subplot(1,2,1)
c41 = categorical(data_v(1:249,4),[0 1],{'No Heart disease','with Heart disease'});
histogram(c41,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
subplot(1,2,2)
c42 = categorical(data_v(250:end,4),[0 1],{'No Heart disease','with Heart disease'});
histogram(c42,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
%%   5. distribution of marriage
figure()
subplot(1,2,1)
c51 = categorical(data_v(1:249,5),[0 1],{'single','married'});
histogram(c51,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
subplot(1,2,2)
c52 = categorical(data_v(250:end,5),[0 1],{'single','married'});
histogram(c52,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
%%   6. distribution of work type
figure()
subplot(1,2,1)
c61 = categorical(data_v(1:249,6),[0 1 2 3 4],{'children',' Never worked','Govt job','Private','Self employed'});
histogram(c61,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
subplot(1,2,2)
ylim([0 250])
c62 = categorical(data_v(250:end,6),[0 1 2 3 4],{'children',' Never worked','Govt job','Private','Self employed'});
histogram(c62,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
%%   7.distribution place
figure()
subplot(1,2,1)
c71 = categorical(data_v(1:249,7),[0 1],{'Urban','Rural'});
histogram(c71,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');

ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250]) 

subplot(1,2,2)
c82 = categorical(data_v(250:end,7),[0 1],{'Urban','Rural'});
histogram(c82,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250])
%%   10 . distribution of smoke status
figure()
subplot(1,2,1)
c81 = categorical(data_v(1:249,10),[0 1 2 3],{'Unknown','never smoked','formerly smoked','smokes'});
histogram(c81,'BarWidth',0.5,'Facecolor','r');
title('stroke class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250]) 

subplot(1,2,2)
c82 = categorical(data_v(250:end,10),[0 1 2 3],{'Unknown','never smoked','formerly smoked','smokes'});
h12 = histogram(c82,'BarWidth',0.5,'Facecolor','g');
title('Healthy class',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
ylabel('Num','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylim([0 250]) 
%% C. scatter
%%    scater of sex&age
figure()
gscatter(data_v(:,1),data_v(:,2),data_v(:,11),'gr','xo',[6 10]);
title('Distribution of sex and age',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('sex','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
legend('Healthy','stroke');

%%   gscater 
figure()
x = data_v(:,2);                % age
y = data_v(:,9);                % BMI
g = {data_v(:,4),data_v(:,11)}; % heart desease & label(healthy&stroke)
gscatter(x,y,g,'rkmb','o*v^',[6 12],'on','Age','BMI')

xlabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('BMI','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
legend('no heart desease- no stroke',...
    'no heart deseae with stroke','heart desease-no stroke',...
    'heart desease with stroke','Location','northeastoutside')
%% scatter age & glucose
figure()
x = data_v(:,2);                % age
y = data_v(:,8);                % avg_glucose_level
g = {data_v(:,11)};             % label(healthy&stroke)
gscatter(x,y,g,'gr','o*',[6 12])
title('Distribution of age & glucose level',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('Avg. glucose level','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
legend('Healthy','stroke');

%%    gscatter age & BMI
figure()
x = data_v(:,2);                % age
y = data_v(:,9);                % BMI
g = {data_v(:,11)};             % label(healthy&stroke)
gscatter(x,y,g,'gr','o*',[6 12])
title('Distribution of age & BMI',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('age','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('BMI','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
legend('Healthy','stroke');
%%   gscatter glucose & BMI
figure()
x = data_v(:,9);                % BMI
y = data_v(:,8);                % Glucose
g = {data_v(:,11)};             % label(healthy&stroke)
gscatter(x,y,g,'gr','o*',[12 12])
title('Distribution of glucose level & BMI',...
      'fontsize',Ft,...
      'FontName','Times New Roman');
xlabel('BMI','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
ylabel('Avg. glucose level','FontSize',Fs,...
       'FontWeight','bold',...
       'FontName','Times New Roman');
legend('Healthy','stroke');

mean_glucose_s = mean(data_v(1:249,8))
mean_glucose_h = mean(data_v(250:end,8))

mean_BMI_s = mean(data_v(1:249,9))
mean_BMI_h = mean(data_v(250:end,9))

%% features Correlation
feat = data_v(:,1:10);
feature_correlation_matrix = corr(feat,feat)

